package com.innomind.msffinance.web.model;
// Generated Aug 21, 2016 3:30:17 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * MsfClientAltPhone generated by hbm2java
 */
@Entity
@Table(name = "msf_client_alt_phone", catalog = "msfinance")
public class MsfClientAltPhone implements java.io.Serializable {

	private Integer altPhoneId;
	private MsfClient msfClient;
	private String altPhoneName;
	private String altPhoneNumber;

	public MsfClientAltPhone() {
	}

	public MsfClientAltPhone(MsfClient msfClient, String altPhoneName, String altPhoneNumber) {
		this.msfClient = msfClient;
		this.altPhoneName = altPhoneName;
		this.altPhoneNumber = altPhoneNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "alt_phone_id", unique = true, nullable = false)
	public Integer getAltPhoneId() {
		return this.altPhoneId;
	}

	public void setAltPhoneId(Integer altPhoneId) {
		this.altPhoneId = altPhoneId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "client_id", nullable = false)
	@JsonBackReference
	public MsfClient getMsfClient() {
		return this.msfClient;
	}

	public void setMsfClient(MsfClient msfClient) {
		this.msfClient = msfClient;
	}

	@Column(name = "alt_phone_name", nullable = false, length = 65535)
	public String getAltPhoneName() {
		return this.altPhoneName;
	}

	public void setAltPhoneName(String altPhoneName) {
		this.altPhoneName = altPhoneName;
	}

	@Column(name = "alt_phone_number", nullable = false, length = 10)
	public String getAltPhoneNumber() {
		return this.altPhoneNumber;
	}

	public void setAltPhoneNumber(String altPhoneNumber) {
		this.altPhoneNumber = altPhoneNumber;
	}

}
