package com.innomind.msffinance.web.model;
// Generated Aug 21, 2016 3:30:17 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * MsfClientDocument generated by hbm2java
 */
@Entity
@Table(name = "msf_client_document", catalog = "msfinance")
public class MsfClientDocument implements java.io.Serializable {

	private Integer documentId;
	private MsfClient msfClient;
	private int documentTypeId;

	public MsfClientDocument() {
	}

	public MsfClientDocument(MsfClient msfClient, int documentTypeId) {
		this.msfClient = msfClient;
		this.documentTypeId = documentTypeId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "document_id", unique = true, nullable = false)
	public Integer getDocumentId() {
		return this.documentId;
	}

	public void setDocumentId(Integer documentId) {
		this.documentId = documentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "client_id", nullable = false)
	@JsonBackReference
	public MsfClient getMsfClient() {
		return this.msfClient;
	}

	public void setMsfClient(MsfClient msfClient) {
		this.msfClient = msfClient;
	}

	@Column(name = "document_type_id", nullable = false)
	public int getDocumentTypeId() {
		return this.documentTypeId;
	}

	public void setDocumentTypeId(int documentTypeId) {
		this.documentTypeId = documentTypeId;
	}

}
