package com.innomind.msffinance.web.model;
// Generated Aug 14, 2016 4:56:02 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MsfClientInterest generated by hbm2java
 */
@Entity
@Table(name = "msf_client_interest", catalog = "msf_finance")
public class MsfClientInterest implements java.io.Serializable {

	private Integer interestId;
	private Integer statusId;
	private MsfClient msfClient;
	private String interestAmount;
	private Date interestDate;
	private String interestPaidAmount;
	private String interestPrevBal;
	private String interestBal;
	private Date createdOn;
	private Date updatedOn;

	public MsfClientInterest() {
	}

	public MsfClientInterest(Integer statusId, MsfClient msfClient, String interestAmount, Date interestDate,
			String interestPaidAmount, Date createdOn) {
		this.statusId = statusId;
		this.msfClient = msfClient;
		this.interestAmount = interestAmount;
		this.interestDate = interestDate;
		this.interestPaidAmount = interestPaidAmount;
		this.createdOn = createdOn;
	}

	public MsfClientInterest(Integer statusId, MsfClient msfClient, String interestAmount, Date interestDate,
			String interestPaidAmount, Date createdOn, Date updatedOn) {
		this.statusId = statusId;
		this.msfClient = msfClient;
		this.interestAmount = interestAmount;
		this.interestDate = interestDate;
		this.interestPaidAmount = interestPaidAmount;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "interest_id", unique = true, nullable = false)
	public Integer getInterestId() {
		return this.interestId;
	}

	public void setInterestId(Integer interestId) {
		this.interestId = interestId;
	}

	@Column(name = "status_id", nullable = false)
	public Integer getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Integer msfStatus) {
		this.statusId = msfStatus;
	}
	
	@ManyToOne(optional = false, fetch = FetchType.LAZY)
	@JoinColumn(name = "client_id", nullable = false)
	public MsfClient getMsfClient() {
		return this.msfClient;
	}

	public void setMsfClient(MsfClient msfClient) {
		this.msfClient = msfClient;
	}

	@Column(name = "interest_amount", nullable = false, length = 50)
	public String getInterestAmount() {
		return this.interestAmount;
	}

	public void setInterestAmount(String interestAmount) {
		this.interestAmount = interestAmount;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "interest_date", nullable = false, length = 10)
	public Date getInterestDate() {
		return this.interestDate;
	}

	public void setInterestDate(Date interestDate) {
		this.interestDate = interestDate;
	}

	@Column(name = "interest_paid_amount", nullable = false, length = 50)
	public String getInterestPaidAmount() {
		return this.interestPaidAmount;
	}

	public void setInterestPaidAmount(String interestPaidAmount) {
		this.interestPaidAmount = interestPaidAmount;
	}
	
	@Column(name = "interest_prev_bal", nullable = false, length = 50)
	public String getInterestPrevBal() {
		return interestPrevBal;
	}

	public void setInterestPrevBal(String interestPrevBal) {
		this.interestPrevBal = interestPrevBal;
	}
	
	@Column(name = "interest_bal", nullable = false, length = 50)
	public String getInterestBal() {
		return interestBal;
	}

	public void setInterestBal(String interestBal) {
		this.interestBal = interestBal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_on", nullable = false, length = 10)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_on", length = 10)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

}
