package com.innomind.msffinance.web.model;
// Generated Aug 21, 2016 3:30:17 PM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.Cascade;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * MsfClient generated by hbm2java
 */
@Entity
@Table(name = "msf_client", catalog = "msfinance")
public class MsfClient implements java.io.Serializable {

	private Integer clientId;
	private String clientName;
	private String clientAddress;
	private String clientPhone;
	private String clientAmount;
	private int tenureTypeId;
	private int clientTenure;
	private int interestTypeId;
	private String clientInterest;
	private byte[] clientPhoto;
	private Date createdOn;
	private Date updatedOn;
	private Set<MsfClientDocument> msfClientDocuments = new HashSet<MsfClientDocument>(0);
	private Set<MsfClientAltPhone> msfClientAltPhones = new HashSet<MsfClientAltPhone>(0);
	private String interestAmount;
	private String clientPhotoString;
	private int statusId;
	private String statusDesc;
	private int diff;

	public MsfClient() {
	}

	public MsfClient(String clientName, String clientAddress, String clientPhone, 
			String clientAmount, int tenureTypeId, int clientTenure, 
			int interestTypeId, String clientInterest, Date createdOn) {
		this.clientName = clientName;
		this.clientAddress = clientAddress;
		this.clientPhone = clientPhone;
		this.clientAmount = clientAmount;
		this.tenureTypeId = tenureTypeId;
		this.clientTenure = clientTenure;
		this.interestTypeId = interestTypeId;
		this.clientInterest = clientInterest;
		this.createdOn = createdOn;
	}

	public MsfClient(String clientName, String clientAddress, String clientPhone, 
			String clientAmount, int tenureTypeId, int clientTenure, int interestTypeId,
			String clientInterest, byte[] clientPhoto, Date createdOn, Date updatedOn, 
			Set<MsfClientDocument> msfClientDocuments, Set<MsfClientAltPhone> msfClientAltPhones) {
		this.clientName = clientName;
		this.clientAddress = clientAddress;
		this.clientPhone = clientPhone;
		this.clientAmount = clientAmount;
		this.tenureTypeId = tenureTypeId;
		this.clientTenure = clientTenure;
		this.interestTypeId = interestTypeId;
		this.clientInterest = clientInterest;
		this.clientPhoto = clientPhoto;
		this.createdOn = createdOn;
		this.updatedOn = updatedOn;
		this.msfClientDocuments = msfClientDocuments;
		this.msfClientAltPhones = msfClientAltPhones;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "client_id", unique = true, nullable = false)
	public Integer getClientId() {
		return this.clientId;
	}

	public void setClientId(Integer clientId) {
		this.clientId = clientId;
	}

	@Column(name = "client_name", nullable = false, length = 65535)
	public String getClientName() {
		return this.clientName;
	}

	public void setClientName(String clientName) {
		this.clientName = clientName;
	}

	@Column(name = "client_address", nullable = false, length = 500)
	public String getClientAddress() {
		return this.clientAddress;
	}

	public void setClientAddress(String clientAddress) {
		this.clientAddress = clientAddress;
	}

	@Column(name = "client_phone", nullable = false, length = 10)
	public String getClientPhone() {
		return this.clientPhone;
	}

	public void setClientPhone(String clientPhone) {
		this.clientPhone = clientPhone;
	}

	@Column(name = "client_amount", nullable = false, length = 50)
	public String getClientAmount() {
		return this.clientAmount;
	}

	public void setClientAmount(String clientAmount) {
		this.clientAmount = clientAmount;
	}

	@Column(name = "tenure_type_id", nullable = false)
	public int getTenureTypeId() {
		return this.tenureTypeId;
	}

	public void setTenureTypeId(int tenureTypeId) {
		this.tenureTypeId = tenureTypeId;
	}

	@Column(name = "client_tenure", nullable = false)
	public int getClientTenure() {
		return this.clientTenure;
	}

	public void setClientTenure(int clientTenure) {
		this.clientTenure = clientTenure;
	}

	@Column(name = "interest_type_id", nullable = false)
	public int getInterestTypeId() {
		return this.interestTypeId;
	}

	public void setInterestTypeId(int interestTypeId) {
		this.interestTypeId = interestTypeId;
	}

	@Column(name = "client_interest", nullable = false, length = 50)
	public String getClientInterest() {
		return this.clientInterest;
	}

	public void setClientInterest(String clientInterest) {
		this.clientInterest = clientInterest;
	}

	@Column(name = "client_photo")
	public byte[] getClientPhoto() {
		return this.clientPhoto;
	}

	public void setClientPhoto(byte[] clientPhoto) {
		this.clientPhoto = clientPhoto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_on", nullable = false, length = 10)
	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_on", length = 10)
	public Date getUpdatedOn() {
		return this.updatedOn;
	}

	public void setUpdatedOn(Date updatedOn) {
		this.updatedOn = updatedOn;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "msfClient")
	@Column(nullable = true)
	@JsonManagedReference
	@Cascade(value = org.hibernate.annotations.CascadeType.ALL)
	public Set<MsfClientDocument> getMsfClientDocuments() {
		return this.msfClientDocuments;
	}

	public void setMsfClientDocuments(Set<MsfClientDocument> msfClientDocuments) {
		this.msfClientDocuments = msfClientDocuments;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "msfClient")
	@Column(nullable = true)
    @JsonManagedReference
    @Cascade(value = org.hibernate.annotations.CascadeType.ALL)
	public Set<MsfClientAltPhone> getMsfClientAltPhones() {
		return this.msfClientAltPhones;
	}

	public void setMsfClientAltPhones(Set<MsfClientAltPhone> msfClientAltPhones) {
		this.msfClientAltPhones = msfClientAltPhones;
	}
	
	@Transient
	public String getInterestAmount() {
		return interestAmount;
	}

	public void setInterestAmount(String interestAmount) {
		this.interestAmount = interestAmount;
	}
	
	@Transient	
	public String getClientPhotoString() {
		return clientPhotoString;
	}

	public void setClientPhotoString(String clientPhotoString) {
		this.clientPhotoString = clientPhotoString;
	}
	
	@Transient
	public int getStatusId() {
		return statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}
	
	@Transient
	public String getStatusDesc() {
		return statusDesc;
	}

	public void setStatusDesc(String statusDesc) {
		this.statusDesc = statusDesc;
	}
	
	@Transient
	public int getDiff() {
		return diff;
	}

	public void setDiff(int diff) {
		this.diff = diff;
	}
}
