package com.innomind.msffinance.web.model;
// Generated Jul 31, 2016 12:24:15 PM by Hibernate Tools 4.3.1.Final

import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MsfDocumentType generated by hbm2java
 */
@Entity
@Table(name = "msf_document_type", catalog = "msfinance")
public class MsfDocumentType implements java.io.Serializable {

	private Integer documentTypeId;
	private String documentTypeName;
	private String documentTypeDesc;
	//private Set<MsfClientDocument> msfClientDocuments = new HashSet<MsfClientDocument>(0);

	public MsfDocumentType() {
	}

	public MsfDocumentType(String documentTypeName, String documentTypeDesc) {
		this.documentTypeName = documentTypeName;
		this.documentTypeDesc = documentTypeDesc;
	}

	public MsfDocumentType(String documentTypeName, String documentTypeDesc,
			Set<MsfClientDocument> msfClientDocuments) {
		this.documentTypeName = documentTypeName;
		this.documentTypeDesc = documentTypeDesc;
		//this.msfClientDocuments = msfClientDocuments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "document_type_id", unique = true, nullable = false)
	public Integer getDocumentTypeId() {
		return this.documentTypeId;
	}

	public void setDocumentTypeId(Integer documentTypeId) {
		this.documentTypeId = documentTypeId;
	}

	@Column(name = "document_type_name", nullable = false, length = 10)
	public String getDocumentTypeName() {
		return this.documentTypeName;
	}

	public void setDocumentTypeName(String documentTypeName) {
		this.documentTypeName = documentTypeName;
	}

	@Column(name = "document_type_desc", nullable = false, length = 65535)
	public String getDocumentTypeDesc() {
		return this.documentTypeDesc;
	}

	public void setDocumentTypeDesc(String documentTypeDesc) {
		this.documentTypeDesc = documentTypeDesc;
	}

	/*@OneToMany(fetch = FetchType.LAZY, mappedBy = "msfDocumentType")
	public Set<MsfClientDocument> getMsfClientDocuments() {
		return this.msfClientDocuments;
	}

	public void setMsfClientDocuments(Set<MsfClientDocument> msfClientDocuments) {
		this.msfClientDocuments = msfClientDocuments;
	}*/

}
