package com.innomind.msffinance.web.model;
// Generated Aug 7, 2016 9:33:02 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MsfInterestType generated by hbm2java
 */
@Entity
@Table(name = "msf_interest_type", catalog = "msfinance")
public class MsfInterestType implements java.io.Serializable {

	private Integer interestTypeId;
	private String interestTypeName;

	public MsfInterestType() {
	}

	public MsfInterestType(String interestTypeName) {
		this.interestTypeName = interestTypeName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "interest_type_id", unique = true, nullable = false)
	public Integer getInterestTypeId() {
		return this.interestTypeId;
	}

	public void setInterestTypeId(Integer interestTypeId) {
		this.interestTypeId = interestTypeId;
	}

	@Column(name = "interest_type_name", nullable = false, length = 10)
	public String getInterestTypeName() {
		return this.interestTypeName;
	}

	public void setInterestTypeName(String interestTypeName) {
		this.interestTypeName = interestTypeName;
	}

}
